### ISSUE TITLE
Extra indentation on EJS statements

### ISSUE THREAD

**Issue by steventartufo** [HiroyukiNIshimura/ejs-beautify#1]
![image](https://user-images.githubusercontent.com/24581422/142769221-26379610-4cbd-4090-b6bf-485f6b0c0994.png)

Hello very helpful plugin thank you. 

Is there a way to also indent EJS statements and the html tags that are wrapped by them? They seem to stack on top of each other.

Similar to this indentation: (which is replaced on save)
![image](https://user-images.githubusercontent.com/24581422/142769292-13d72e1a-8e81-484a-b3a2-ea6b21c62a0c.png)

**Comment by johfer** [comment]
Yep, same question here...

**Comment by HiroyukiNIshimura** [comment]
thank you!

Originally I was having trouble with EJS formatting, and when I ran js-beautify with the erb template, it felt pretty good.
Please take a moment to find out what happens with the js-beautify settings.

**Comment by johfer** [comment]
Hi,

thank you - I looked through the js-beautify options and used "templating": ["erb"] but couldn't find a way to indent EJS code blocks (e.g. the line following an opening bracket "{ %>", as requested here)

**Comment by HiroyukiNIshimura** [comment]
I'm sorry.

I reread the source code of js-beautify and investigated what the settings did not work for ... Unfortunately, there was no setting that gave good results.

The idea seems to be to match the indentation of the HTML that is ultimately rendered by the client as much as possible, rather than what it looks like in the code.

## When formatted in the expected format

```html
  <body>
    <% a.array.forEach(element=> { %>
      <% if (condition) { %>
        <li class="a">
          <div class="b">
            <%- element.name %>
          </div>
        </li>
      <% } else { %>
        <li class="a">
          <div class="b">
            <%- element.age %>
          </div>
        </li>
      <% } %>
      <script>
        function a() {
          if (true) {
            console.log('')
          }
        }
      </script>
    <% }); %>
  </body>
```

HTML rendered in the browser.
In this case, the indentation of the HTML tag will be broken.

```html
  <body>
        <li class="a">
          <div class="b">
            neko
          </div>
        </li>
        <li class="a">
          <div class="b">
            10
          </div>
        </li>
      <script>
        function a() {
          if (true) {
            console.log('')
          }
        }
      </script>
  </body>
```

## The result of formatting by ejs-beautify

```html
  <body>
    <% a.array.forEach(element=> { %>
    <% if (condition) { %>
    <li class="a">
      <div class="b">
        <%- element.name %>
      </div>
    </li>
    <% } else { %>
    <li class="a">
      <div class="b">
        <%- element.age %>
      </div>
    </li>
    <% } %>
    <script>
      function a() {
        if (true) {
          console.log('')
        }
      }
    </script>
    <% }); %>
  </body>
```

In this case, the indentation of the HTML rendered in the browser will be clean.

```html
  <body>
    <li class="a">
      <div class="b">
        neko
      </div>
    </li>
    <li class="a">
      <div class="b">
        10
      </div>
    </li>
    <script>
      function a() {
        if (true) {
          console.log('')
        }
      }
    </script>
  </body>
```

I know how you feel!
Unlike the source code before compiling, the latter seems to be more correct when considering the formatting of the generated HTML.

It is not easy to judge which is correct. It's difficult ... 😅

**Comment by johfer** [comment]
Hi, thanks for taking the time to investigate!

Yes, the latter gives the more accurate HTML output indeed. In that sense the EJS formatter could be described as an HTML formatter that also accepts EJS input.

Again, thanks for investigating. Feel free to close the issue as you see fit.

**Comment by HiroyukiNIshimura** [comment]
thank you!

As one of the ideas, it would be interesting to switch between coding view and rendering view ... whether or not it can be done 😅

**Comment by GeylanKM** [comment]
Hi @HiroyukiNIshimura is it possible that you modify js-beautify to format its code to indent the ejs specific code otherwise its really hard to read even if the indentation of the output html tags are broken

**Comment by GeylanKM** [comment]
even if its just an option that defaults to false
